# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

sorcery_facebook_key: <%= ENV['FACEBOOK_ID'] %>
sorcery_facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
sorcery_facebook_callback_url: http://localhost:3000/oauth/callback?provider=facebook
aws_access_key_id: <%= ENV['S3_KEY'] %>
aws_secret_access_key: <%= ENV['S3_SECRET'] %>
aws_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
sms_username: <%= ENV['SMS_USERNAME'] %>
sms_password: <%= ENV['SMS_PASSWORD'] %>

development:
  secret_key_base: 86950b31c61f6ae9768fc11f10776ed0f49c8dffd07c49ee84cc791a3e4426752a4e7774d961530d1cc5372b451e58ab4f71f0b3c9493ec2712792ceee156129

test:
  secret_key_base: f0f8d46e218abf2459301c292a4a9f25df86a3f229ca8d14fae4b26ab13065c1fe0f0b373f0b6a82c8ab2eac14b7d7cfc6584d0cc216bc2ea49cd98a94caf146

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

